### ISSUE TITLE
Improve module Library user experience

### ISSUE THREAD

**Issue by rkazakov** [BibleQuote/BibleQuote#164]
As a BibleQuote user, I would like to improve module Library user experience, so that I could find work with module more effectively.

<img width="1235" alt="screen shot 2019-01-24 at 11 46 48 pm" src="https://user-images.githubusercontent.com/168863/51680986-661d5800-2037-11e9-8b73-b55ad8841cef.png">

**Screenshot 1**

<img width="598" alt="screen shot 2019-02-01 at 8 46 59 am" src="https://user-images.githubusercontent.com/168863/52087678-30abd800-25fe-11e9-8cd3-c2794760240d.png">

**Screenshot 2**

**Acceptance criteria**:
- Search:
   - Search is performed for `Name` and `Author` attributes for native modules.
   - Search is performed for `Name` attribute for MyBible dictionaries.
   - The search is **NOT** case sensitive.
- Total number of modules are shown. When searching show how many found.
- Add the ability to change how list of modules displays: `Cover View`, `Tile View` and `Details View`.
- Picture rendering problem is fixed (See **Screenshot 2**).
- Modules without images show `BibleQuote` or `MyBible` icons in the `Library`.

_Technical details:_
- What are other types that TVirtualListView can render?
- Default images:
   - [BibleQuote no text](https://user-images.githubusercontent.com/168863/52308262-f9b83680-29f0-11e9-858b-34021d3a56eb.png)
   - [MyBible no text](https://user-images.githubusercontent.com/168863/52308263-f9b83680-29f0-11e9-8582-a9d39bf1ebd8.png)

**Comment by djtsov** [comment]
The TVirtualListView can display only Tile and Detail View. For Cover mode it's needed to use TListView.

**Comment by rkazakov** [comment]
Completed in PR https://github.com/BibleQuote/BibleQuote/pull/178.
