### ISSUE TITLE
Any way to build this program for Mac 

### ISSUE THREAD

**Issue by sittim** [BibleQuote/BibleQuote#241]
As a BibleQuote user, I would like to not have to run it through wine, but would love to run it as a native app.  

**Acceptance criteria**:
- Ability to build and run on Mac or Linux OS

_Technical details:_
- ...

**Comment by rkazakov** [comment]
Hi @sittim,

Are you a developer? Any thoughts on this story?

Thanks,

Ruslan

**Comment by sittim** [comment]
@rkazakov I am an embedded developer, not a software developer, so I am not brave enough to tackle this.

**Comment by sittim** [comment]
@rkazakov I have been using the BiblQuote in Mac OS through [Wine](https://wiki.winehq.org/MacOS), it works very well except the US does not look as crisp.

**Comment by rkazakov** [comment]
@sittim 
Did you mean UI? 🙂
Try running BibleQuote with Windows10 in VirtualBox. Works well for me.

**Comment by sittim** [comment]
@rkazakov, yes I mean UI, sorry.  Wine is simpler and quicker than Windows 10.  Plus to run it, a licence is required, which I do not have.  For that reason, Wine will do.
