### ISSUE TITLE
Fix error with loading modules

### ISSUE THREAD

**Issue by rkazakov** [BibleQuote/BibleQuote#245]
As a BibleQuote user, I would like to fix error with loading modules, so that I could download modules.

![image](https://user-images.githubusercontent.com/168863/81807242-154dad80-9561-11ea-986e-6fc8befa783a.png)

**Acceptance criteria**:
- Fix the error on the above screenshot.
- Download module in the library on double click.

**Comment by snejinka894-prog** [comment]
А как обычному пользователю это применить? Я не разбираюсь в этом, помогите, пожалуйста.
