### ISSUE TITLE
Move BibleQuote modules into 'Modules' sub folder

### ISSUE THREAD

**Issue by rkazakov** [BibleQuote/BibleQuote#8]
As BibleQuote user, I would like to move my modules into `Modules` sub folder, so that they do not clutter application's main folder.

At the moment modules are loaded from BibleQuote main folder.

**Acceptance criteria**:

_Modules_
- `Modules` folder contains 5 folders: `Bibles`, `Commentaries`, `Dictionaries`, `Strongs`, `Books` and `Compressed`
- `Bibles` are loaded from `Modules\Bibles` sub folder
- `Commentaries` are loaded from `Modules\Commentaries` sub folder
- `Dictionaries` are loaded from `Modules\Dictionaries` sub folder
- `Books` (everything else) are loaded from `Modules\Books` sub folder
- `Compressed modules` are loaded from `Modules\Compressed` sub folder
- `Commentary-TSK` module is loaded from `Modules\Commentaries\Commentary-TSK` sub folder

_Strongs_
- `Strongs` module is loaded from `Modules\Strongs` sub folder
- `StrongsDirectory` configuration property inside `bibleqt.ini` is relative to `Modules\Strongs`

_Build_
- `Modules` folder is copied to `Output\Modules` sub folder during build stage
- `Output` folder is removed from source control

_MainForm Tabs_
- Dictionaries (tab 3 from the left) loads dictionaries from `Modules\Dictionaries`
- Strongs (tab 4 from the left) loads Strongs dictionary (if available) based on the active Bible translation
- Commentaries (tab 5 from the left) loads commentaries from `Modules\Commentaries`

**Comment by rgilmutdinov** [comment]
Некоторые детали, на которые стоит обратить внимания при разработке:

- файл модуля `BibleQt.ini` содержит параметр `Bible=Y/N`. Ставится Y если модуль - Библия или комментарий, N если модуль - книга.
В новой структуре каталогов предполагается этот параметр игнорировать, полагаясь только на расположение модуля. Если модуль содержится в папке `Modules\Bibles`, то считать его Библией, если в папке `Modules\Books`, то считать его книгой.

- файл модуля `BibleQt.ini` содержит параметр `StrongsDirectory`. Он задает путь к директории с номерами Стронга, которая соответствует модулю.
Поскольку Strongs модули перемещаются в папку Modules\Dictionaries, то при поиске словарей с номерами Стронга к значению параметра `StrongsDirectory` автоматически добавлять `Modules\Dictionaries` в качестве префикса.

- задача предполагает фиксацию структуры каталогов, используемых приложением. Однако, параметр `StrongsDirectory` даёт возможность эту структуру нарушить. 
Пока оставляем этот параметр, меняем только способ обработки как указано выше.

**Comment by rkazakov** [comment]
I would like to continue working with Strongs dictionary even if I switched to other Bible translation that does not support Strongs:

![screen shot 2018-04-18 at 4 24 58 pm](https://user-images.githubusercontent.com/168863/38914933-15770562-4325-11e8-9ba7-accbca58a56a.png)

Issue with commentaries:

![screen shot 2018-04-18 at 4 26 51 pm](https://user-images.githubusercontent.com/168863/38914994-53bdeca0-4325-11e8-9e69-d51a2205e72c.png)

**Comment by rkazakov** [comment]
Completed in PR https://github.com/BibleQuote/BibleQuote/pull/58.
